In [1]:
!sudo apt-get update -qq
!sudo apt-get install -y postgresql postgresql-contrib

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcommon-sense-perl libjson-perl libjson-xs-perl libllvm14 libpq-dev libpq5
  libtypes-serialiser-perl logrotate netbase postgresql-14
  postgresql-client-14 postgresql-client-common postgresql-common ssl-cert
  sysstat
Suggested packages:
  postgresql-doc-14 bsd-mailx | mailx postgresql-doc isag
The following NEW packages will be installed:
  libcommon-sense-perl libjson-perl libjson-xs-perl libllvm14
  libtypes-serialiser-perl logrotate netbase postgresql postgresql-14
  postgresql-client-14 postgresql-client-common postgresql-common
  postgresql-contrib ssl-cert sysstat
The following packages will be upgraded:
  libpq-dev libpq5
2 upgraded, 15 newly installed, 0 to remove and 190 not upgraded.
Need to get 42.8 MB of archives.
After this operation, 162 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 logrotate amd64 3.19.0-1ubuntu1.1 [54.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 netbase all 6.3 [12.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcommon-sense-perl amd64 3.75-2build1 [21.1 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjson-perl all 4.04000-1 [81.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtypes-serialiser-perl all 1.01-1 [11.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjson-xs-perl amd64 4.040-0ubuntu0.22.04.1 [87.0 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libllvm14 amd64 1:14.0.0-1ubuntu1.1 [24.0 MB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpq-dev amd64 14.24-0ubuntu0.22.04.1 [149 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpq5 amd64 14.24-0ubuntu0.22.04.1 [157 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 postgresql-client-common all 238 [29.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 postgresql-client-14 amd64 14.24-0ubuntu0.22.04.1 [1,253 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 ssl-cert all 1.1.2 [17.4 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 postgresql-common all 238 [169 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 postgresql-14 amd64 14.24-0ubuntu0.22.04.1 [16.3 MB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 postgresql all 14+238 [3,288 B]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 postgresql-contrib all 14+238 [3,292 B]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 sysstat amd64 12.5.2-2ubuntu0.2 [487 kB]
Fetched 42.8 MB in 3s (15.9 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 17.)
debconf: falling back to frontend: Readline
Preconfiguring packages ...
Selecting previously unselected package logrotate.
(Reading database ... 121026 files and directories currently installed.)
Preparing to unpack .../00-logrotate_3.19.0-1ubuntu1.1_amd64.deb ...
Unpacking logrotate (3.19.0-1ubuntu1.1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../01-netbase_6.3_all.deb ...
Unpacking netbase (6.3) ...
Selecting previously unselected package libcommon-sense-perl:amd64.
Preparing to unpack .../02-libcommon-sense-perl_3.75-2build1_amd64.deb ...
Unpacking libcommon-sense-perl:amd64 (3.75-2build1) ...
Selecting previously unselected package libjson-perl.
Preparing to unpack .../03-libjson-perl_4.04000-1_all.deb ...
Unpacking libjson-perl (4.04000-1) ...
Selecting previously unselected package libtypes-serialiser-perl.
Preparing to unpack .../04-libtypes-serialiser-perl_1.01-1_all.deb ...
Unpacking libtypes-serialiser-perl (1.01-1) ...
Selecting previously unselected package libjson-xs-perl.
Preparing to unpack .../05-libjson-xs-perl_4.040-0ubuntu0.22.04.1_amd64.deb ...
Unpacking libjson-xs-perl (4.040-0ubuntu0.22.04.1) ...
Selecting previously unselected package libllvm14:amd64.
Preparing to unpack .../06-libllvm14_1%3a14.0.0-1ubuntu1.1_amd64.deb ...
Unpacking libllvm14:amd64 (1:14.0.0-1ubuntu1.1) ...
Preparing to unpack .../07-libpq-dev_14.24-0ubuntu0.22.04.1_amd64.deb ...
Unpacking libpq-dev (14.24-0ubuntu0.22.04.1) over (14.22-0ubuntu0.22.04.1) ...
Preparing to unpack .../08-libpq5_14.24-0ubuntu0.22.04.1_amd64.deb ...
Unpacking libpq5:amd64 (14.24-0ubuntu0.22.04.1) over (14.22-0ubuntu0.22.04.1) ...
Selecting previously unselected package postgresql-client-common.
Preparing to unpack .../09-postgresql-client-common_238_all.deb ...
Unpacking postgresql-client-common (238) ...
Selecting previously unselected package postgresql-client-14.
Preparing to unpack .../10-postgresql-client-14_14.24-0ubuntu0.22.04.1_amd64.deb ...
Unpacking postgresql-client-14 (14.24-0ubuntu0.22.04.1) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../11-ssl-cert_1.1.2_all.deb ...
Unpacking ssl-cert (1.1.2) ...
Selecting previously unselected package postgresql-common.
Preparing to unpack .../12-postgresql-common_238_all.deb ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Unpacking postgresql-common (238) ...
Selecting previously unselected package postgresql-14.
Preparing to unpack .../13-postgresql-14_14.24-0ubuntu0.22.04.1_amd64.deb ...
Unpacking postgresql-14 (14.24-0ubuntu0.22.04.1) ...
Selecting previously unselected package postgresql.
Preparing to unpack .../14-postgresql_14+238_all.deb ...
Unpacking postgresql (14+238) ...
Selecting previously unselected package postgresql-contrib.
Preparing to unpack .../15-postgresql-contrib_14+238_all.deb ...
Unpacking postgresql-contrib (14+238) ...
Selecting previously unselected package sysstat.
Preparing to unpack .../16-sysstat_12.5.2-2ubuntu0.2_amd64.deb ...
Unpacking sysstat (12.5.2-2ubuntu0.2) ...
Setting up logrotate (3.19.0-1ubuntu1.1) ...
Created symlink /etc/systemd/system/timers.target.wants/logrotate.timer → /lib/systemd/system/logrotate.timer.
Setting up libpq5:amd64 (14.24-0ubuntu0.22.04.1) ...
Setting up libcommon-sense-perl:amd64 (3.75-2build1) ...
Setting up libpq-dev (14.24-0ubuntu0.22.04.1) ...
Setting up ssl-cert (1.1.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Setting up libllvm14:amd64 (1:14.0.0-1ubuntu1.1) ...
Setting up libtypes-serialiser-perl (1.01-1) ...
Setting up libjson-perl (4.04000-1) ...
Setting up netbase (6.3) ...
Setting up sysstat (12.5.2-2ubuntu0.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline

Creating config file /etc/default/sysstat with new version
update-alternatives: using /usr/bin/sar.sysstat to provide /usr/bin/sar (sar) in auto mode
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-collect.timer → /lib/systemd/system/sysstat-collect.timer.
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-summary.timer → /lib/systemd/system/sysstat-summary.timer.
Created symlink /etc/systemd/system/multi-user.target.wants/sysstat.service → /lib/systemd/system/sysstat.service.
Setting up postgresql-client-common (238) ...
Setting up libjson-xs-perl (4.040-0ubuntu0.22.04.1) ...
Setting up postgresql-client-14 (14.24-0ubuntu0.22.04.1) ...
update-alternatives: using /usr/share/postgresql/14/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
Setting up postgresql-common (238) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Adding user postgres to group ssl-cert

Creating config file /etc/postgresql-common/createcluster.conf with new version
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
Created symlink /etc/systemd/system/multi-user.target.wants/postgresql.service → /lib/systemd/system/postgresql.service.
Setting up postgresql-14 (14.24-0ubuntu0.22.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Creating new PostgreSQL cluster 14/main ...
/usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/14/main --auth-local peer --auth-host scram-sha-256 --no-instructions
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/14/main ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok
update-alternatives: using /usr/share/postgresql/14/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up postgresql-contrib (14+238) ...
Setting up postgresql (14+238) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

In [4]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 36.6 MB/s eta 0:00:0000:0100:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [2]:
!sudo service postgresql start

 * Starting PostgreSQL 14 database server
   ...done.

In [3]:
!sudo -u postgres psql -c "CREATE DATABASE mydb;"

CREATE DATABASE

In [6]:
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

ALTER ROLE

In [7]:
import psycopg2

conn = psycopg2.connect(
    dbname="mydb",
    user="postgres",
    password="postgres",
    host="localhost",
    port="5432"
)

cursor = conn.cursor()

print("Connected successfully!")

Connected successfully!

In [10]:
import pandas as pd

file_path = "/kaggle/input/datasets/yashgoyal78/zomato-delhi-dataset/zomato.csv"

df = pd.read_csv(file_path, encoding="latin1")

print(df.shape)
print(df.columns.tolist())

(9551, 21)
['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address', 'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating', 'Rating color', 'Rating text', 'Votes']

In [11]:
df.head(5)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [12]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/mydb"
)

df.to_sql(
    "restaurants",
    engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully!")

Data loaded successfully!

In [17]:
query = """
SELECT *
FROM restaurants
WHERE 1 = 0;
"""

result = pd.read_sql(query, engine)

result

Empty DataFrame
Columns: [Restaurant ID, Restaurant Name, Country Code, City, Address, Locality, Locality Verbose, Longitude, Latitude, Cuisines, Average Cost for two, Currency, Has Table booking, Has Online delivery, Is delivering now, Switch to order menu, Price range, Aggregate rating, Rating color, Rating text, Votes]
Index: []

[0 rows x 21 columns]

In [19]:
columns = pd.read_sql("""
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name = 'restaurants'
ORDER BY ordinal_position;
""", engine)

columns

             column_name         data_type
0          Restaurant ID            bigint
1        Restaurant Name              text
2           Country Code            bigint
3                   City              text
4                Address              text
5               Locality              text
6       Locality Verbose              text
7              Longitude  double precision
8               Latitude  double precision
9               Cuisines              text
10  Average Cost for two            bigint
11              Currency              text
12     Has Table booking              text
13   Has Online delivery              text
14     Is delivering now              text
15  Switch to order menu              text
16           Price range            bigint
17      Aggregate rating  double precision
18          Rating color              text
19           Rating text              text
20                 Votes            bigint

In [20]:
pd.read_sql("""
SELECT *
FROM restaurants
LIMIT 5;
""", engine)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [41]:
import psycopg2

conn = psycopg2.connect(
    dbname="mydb",
    user="postgres",
    password="postgres",
    host="localhost",
    port="5432"
)

print("Connected!")

Connected!

In [45]:
q0 = """
SELECT
    "Locality",
    "Locality Verbose",
    COUNT(*) AS restaurant_count
FROM restaurants
WHERE "City" = 'New Delhi'
  AND (
      "Locality" ILIKE '%Dwarka%'
      OR "Locality Verbose" ILIKE '%Dwarka%'
  )
GROUP BY
    "Locality",
    "Locality Verbose"
ORDER BY restaurant_count DESC;
"""

import pandas as pd

result = pd.read_sql_query(q0, conn)

result

/tmp/ipykernel_58/1371327921.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(q0, conn)

            Locality              Locality Verbose  restaurant_count
0  Sector 15, Dwarka  Sector 15, Dwarka, New Delhi                 1

In [47]:
conn.rollback()

print("Transaction reset")

Transaction reset

In [49]:
import psycopg2

# Close old connection if it exists
try:
    cursor.close()
    conn.close()
except:
    pass

# Create a completely new connection
conn = psycopg2.connect(
    dbname="mydb",
    user="postgres",
    password="postgres",
    host="localhost",
    port="5432"
)

# Create a new cursor
cursor = conn.cursor()

print("New PostgreSQL connection established!")

New PostgreSQL connection established!

In [50]:
cursor.execute("SELECT 1;")

print(cursor.fetchone())

(1,)

In [51]:
cursor.execute("""
SELECT COUNT(*)
FROM restaurants;
""")

print(cursor.fetchone())

(9551,)

In [65]:
import pandas as pd

def run_query(query):
    cursor.execute(query)
    
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    
    return pd.DataFrame(rows, columns=columns)

In [61]:
conn.rollback()

print("Transaction reset")

Transaction reset

In [67]:
q1 = """
SELECT
    "Restaurant Name",
    "Locality",
    "Cuisines",
    "Aggregate rating",
    "Votes",
    "Average Cost for two"
FROM restaurants
WHERE "City" = 'New Delhi'
  AND "Aggregate rating" > 0
  AND "Has Online delivery" = 'Yes'
ORDER BY
    "Aggregate rating" DESC,
    "Votes" DESC
LIMIT 20;
"""

result = run_query(q1)

result

,Restaurant Name,Locality,Cuisines,Aggregate rating,Votes,Average Cost for two
0,Naturals Ice Cream,Connaught Place,Ice Cream,4.9,2620,150
1,Naturals Ice Cream,Rajouri Garden,Ice Cream,4.7,474,150
2,Zabardast Indian Kitchen,Connaught Place,North Indian,4.7,242,1800
3,Spezia Bistro,Delhi University-GTB Nagar,"Cafe, Continental, Chinese, Italian",4.6,1071,900
4,Greenr Cafe,Shahpur Jat,Cafe,4.6,112,1100
5,Food Scouts,Punjabi Bagh,"North Indian, Chinese, Continental",4.6,61,700
6,Coast Cafe,Hauz Khas Village,"Continental, Kerala",4.5,1033,1400
7,Natural Ice Cream,"JMD Kohinoor Mall, Greater Kailash",Ice Cream,4.5,665,150
8,Owl is Well,Greater Kailash (GK) 1,"Burger, American, Fast Food, Italian, Pizza",4.5,162,1000
9,Natural Ice Cream,Hauz Khas,Ice Cream,4.5,67,150
10,Midnight Hunger Hub,Janakpuri,"North Indian, Fast Food, Italian, Asian",4.5,50,800
11,Gulati,Pandara Road Market,"North Indian, Mughlai",4.4,4373,1500
12,The Hudson Cafe,Delhi University-GTB Nagar,"Cafe, Italian, Continental, Chinese",4.4,1537,850
13,Oh! Calcutta,Nehru Place,"Bengali, Seafood",4.4,1293,1400
14,Rang De Basanti Urban Dhaba,Hauz Khas Village,North Indian,4.4,541,1300
15,The Coffee Shop,PVR Anupam Complex,"Cafe, Italian",4.4,326,1200
16,Locale,PVR Anupam Complex,"North Indian, Chinese, Mexican, Italian, Thai,...",4.4,317,1400
17,Blue Tokai Coffee Roasters,Saket,Cafe,4.4,269,350
18,Food Scouts,Rajouri Garden,"North Indian, Chinese, Continental",4.4,229,700
19,Burgrill,Satyaniketan,"Burger, Fast Food",4.4,178,450

In [68]:
q2 = """
SELECT
    "Restaurant Name",
    "Locality",
    "Cuisines",
    "Aggregate rating",
    "Average Cost for two",
    "Votes",

    ROUND(
        ((
            "Aggregate rating"
            / NULLIF("Average Cost for two", 0)
        ) * 100)::numeric,
        2
    ) AS value_score

FROM restaurants

WHERE "City" = 'New Delhi'
  AND "Aggregate rating" > 0
  AND "Average Cost for two" > 0

ORDER BY value_score DESC
LIMIT 20;
"""

result = run_query(q2)

result

,Restaurant Name,Locality,Cuisines,Aggregate rating,Average Cost for two,Votes,value_score
0,Jung Bahadur Kachori Wala,Chandni Chowk,Street Food,4.1,50,405,8.20
1,Sharma Kachoriwala,Kamla Nagar,Street Food,3.7,50,131,7.40
2,Pakode Ki Dukaan,Karol Bagh,Street Food,3.6,50,35,7.20
3,Duggal Snacks,Mayur Vihar Phase 2,Street Food,3.6,50,32,7.20
4,Pandit Ved Prakash Lemon Wale,Chandni Chowk,"Beverages, Street Food",3.2,50,11,6.40
5,Shahi Kachauri Wale,Uttam Nagar,Street Food,2.8,50,6,5.60
6,Aggarwal Confectionary,Vasundhara Enclave,"Street Food, Bakery",2.8,50,7,5.60
7,Shri Ram Poori Wale,Kirti Nagar,Street Food,2.8,50,8,5.60
8,Shahi Kachauri,Uttam Nagar,Street Food,2.8,50,4,5.60
9,Sita Ram Diwan Chand,Paharganj,Street Food,4.3,100,1317,4.30
10,Cool Point,Jama Masjid,"Desserts, Beverages",4.2,100,69,4.20
11,Ashok Chaat Corner,Chawri Bazar,Street Food,4.1,100,118,4.10
12,Kumar Samose Wala,Karampura,Street Food,4.1,100,187,4.10
13,Old Famous Jalebi Wala,Chandni Chowk,"Mithai, Street Food",3.9,100,752,3.90
14,Bansal Sweets,Pitampura,Mithai,3.9,100,91,3.90
15,Natraj Dahi Bhalle Wala,Chandni Chowk,Street Food,3.9,100,1487,3.90
16,Kev's,Satyaniketan,Fast Food,3.9,100,184,3.90
17,Kallan Sweets,Jama Masjid,Mithai,3.8,100,75,3.80
18,Amritsari Lassi Wala,Chandni Chowk,Beverages,3.8,100,112,3.80
19,Chocolatiers - The Chocolate Boutique,Chittaranjan Park,Desserts,3.8,100,112,3.80

In [71]:
q3 = """
SELECT
    "Locality",
    COUNT(*) AS top_restaurant_count,

    ROUND(
        AVG("Aggregate rating")::numeric,
        2
    ) AS average_rating,

    ROUND(
        AVG("Votes")::numeric,
        0
    ) AS average_votes

FROM restaurants

WHERE "City" = 'New Delhi'
  AND "Aggregate rating" >= 4.0

GROUP BY "Locality"

HAVING COUNT(*) >= 5

ORDER BY
    top_restaurant_count DESC,
    average_rating DESC

LIMIT 15;
"""

result = run_query(q3)

result

,Locality,top_restaurant_count,average_rating,average_votes
0,Connaught Place,32,4.18,1318
1,Rajouri Garden,24,4.26,507
2,Greater Kailash (GK) 1,17,4.16,231
3,Satyaniketan,15,4.15,620
4,Khan Market,14,4.19,1107
5,Defence Colony,13,4.12,360
6,Shahpur Jat,10,4.19,144
7,Greater Kailash (GK) 2,9,4.23,315
8,Malviya Nagar,9,4.10,160
9,Hauz Khas Village,8,4.24,1765
10,"Select Citywalk Mall, Saket",8,4.18,522
11,Delhi University-GTB Nagar,7,4.29,1410
12,Vijay Nagar,7,4.24,1037
13,Safdarjung,7,4.16,705
14,Netaji Subhash Place,6,4.07,328

In [73]:
q4 = """

SELECT
    "Locality",
    COUNT(DISTINCT "Cuisines") AS distinct_cuisine_count
FROM restaurants
GROUP BY "Locality"
ORDER BY distinct_cuisine_count DESC
LIMIT 10;
"""

result = run_query(q4)
result

                 Locality  distinct_cuisine_count
0         Connaught Place                      90
1          Rajouri Garden                      71
2            Satyaniketan                      61
3           Malviya Nagar                      60
4          Defence Colony                      55
5               Sector 18                      52
6              Safdarjung                      52
7  Greater Kailash (GK) 2                      50
8  Greater Kailash (GK) 1                      50
9              Karol Bagh                      47

In [75]:
q5 = """
SELECT
    CASE
        WHEN "Average Cost for two" <= 300
            THEN 'Budget (<= 300)'

        WHEN "Average Cost for two" <= 700
            THEN 'Mid-Range (301-700)'

        WHEN "Average Cost for two" <= 1500
            THEN 'Premium (701-1500)'

        ELSE 'Luxury (> 1500)'
    END AS cost_bucket,

    COUNT(*) AS restaurant_count,

    ROUND(
        AVG("Aggregate rating")::numeric,
        2
    ) AS average_rating,

    ROUND(
        AVG("Votes")::numeric,
        0
    ) AS average_votes

FROM restaurants

WHERE "Aggregate rating" > 0
  AND "Average Cost for two" > 0

GROUP BY cost_bucket

ORDER BY
    average_rating DESC;
"""

result = run_query(q5)
result

           cost_bucket  restaurant_count average_rating average_votes
0      Luxury (> 1500)               573           3.77           538
1   Premium (701-1500)              1407           3.58           353
2      Budget (<= 300)              2208           3.51           156
3  Mid-Range (301-700)              3197           3.26           109

In [77]:
q6 = """
SELECT
    "Has Online delivery",
    "Has Table booking",

    COUNT(*) AS restaurant_count,

    ROUND(
        AVG("Aggregate rating")::numeric,
        2
    ) AS average_rating,

    ROUND(
        AVG("Votes")::numeric,
        0
    ) AS average_votes

FROM restaurants

WHERE "Aggregate rating" > 0

GROUP BY
    "Has Online delivery",
    "Has Table booking"

ORDER BY average_rating DESC;
"""

result = run_query(q6)
result

,Has Online delivery,Has Table booking,restaurant_count,average_rating,average_votes
0,Yes,Yes,433,3.61,476
1,No,Yes,678,3.57,299
2,No,No,4370,3.45,178
3,Yes,No,1922,3.33,162

In [78]:
q7 = """
SELECT
    "Cuisines",

    COUNT(*) AS restaurant_count,

    ROUND(
        AVG("Average Cost for two")::numeric,
        2
    ) AS average_cost,

    ROUND(
        AVG("Aggregate rating")::numeric,
        2
    ) AS average_rating

FROM restaurants

WHERE "City" = 'New Delhi'
  AND "Average Cost for two" > 0

GROUP BY "Cuisines"

HAVING COUNT(*) >= 5

ORDER BY average_cost DESC

LIMIT 15;
"""

result = run_query(q7)
result

,Cuisines,restaurant_count,average_cost,average_rating
0,Modern Indian,5,2980.00,4.58
1,Continental,9,2444.44,3.58
2,"Continental, North Indian, Italian",5,2320.00,3.56
3,Finger Food,30,2293.33,2.68
4,Italian,12,1975.00,3.16
5,"North Indian, Continental, Italian",6,1750.00,3.78
6,"Continental, North Indian, Chinese",5,1570.00,3.40
7,Asian,7,1500.00,2.49
8,"Continental, Italian",8,1406.25,3.49
9,"Finger Food, North Indian, Italian",5,1390.00,3.44
10,"North Indian, Chinese, Continental, Italian",10,1295.00,3.62
11,"North Indian, Continental",16,1212.50,2.99
12,"North Indian, Chinese, Italian, Continental",6,1200.00,3.38
13,Mexican,6,1116.67,3.05
14,"North Indian, Chinese, Italian",7,1092.86,3.07

In [80]:
q8 = """
SELECT
    "Locality",

    COUNT(*) AS restaurant_count,

    ROUND(
        AVG("Aggregate rating")::numeric,
        2
    ) AS average_rating,

    SUM("Votes") AS total_votes,

    ROUND(
        AVG("Votes")::numeric,
        0
    ) AS average_votes

FROM restaurants

WHERE "City" = 'New Delhi'
  AND "Aggregate rating" > 0

GROUP BY "Locality"

HAVING COUNT(*) >= 5

ORDER BY
    average_rating DESC,
    total_votes DESC

LIMIT 15;
"""

result = run_query(q8)
result

,Locality,restaurant_count,average_rating,total_votes,average_votes
0,"Radisson Blu Plaza Delhi, Mahipalpur",6,3.95,1225,204
1,"Shangri La's - Eros hotel, Janpath",5,3.88,626,125
2,"Sangam Courtyard, RK Puram",7,3.87,1871,267
3,Pandara Road Market,10,3.86,7978,798
4,Hauz Khas Village,24,3.85,32573,1357
5,Khan Market,43,3.80,28463,662
6,"Hyatt Regency, Bhikaji Cama Place",6,3.80,1513,252
7,Chawri Bazar,12,3.80,1410,118
8,"The Taj Mahal Hotel, Mansingh Road",7,3.79,1976,282
9,Connaught Place,119,3.78,128107,1077
10,"The Leela Palace, Chanakyapuri",5,3.78,709,142
11,"Select Citywalk Mall, Saket",25,3.76,9054,362
12,"DLF Promenade Mall, Vasant Kunj",13,3.76,1946,150
13,"Ansal Plaza Mall, Khel Gaon Marg",8,3.75,875,109
14,"ITC Maurya, Chanakyapuri",6,3.73,3121,520

In [81]:
q9 = """
WITH ranked_restaurants AS (
    SELECT
        "Restaurant Name",
        "Locality",
        "Aggregate rating",
        "Votes",
        "Average Cost for two",

        RANK() OVER (
            PARTITION BY "Locality"
            ORDER BY
                "Aggregate rating" DESC,
                "Votes" DESC
        ) AS locality_rank

    FROM restaurants

    WHERE "City" = 'New Delhi'
      AND "Aggregate rating" > 0
)

SELECT *
FROM ranked_restaurants
WHERE locality_rank <= 3
ORDER BY "Locality", locality_rank;
"""

result = run_query(q9)
result

,Restaurant Name,Locality,Aggregate rating,Votes,Average Cost for two,locality_rank
0,Rustom's Parsi Bhonu,Adchini,4.2,665,1500,1
1,Nariyal Cafe,Adchini,4.2,46,1200,2
2,Chateau,Adchini,4.0,40,1600,3
3,Sultanat,"Aditya Mega Mall, Karkardooma",3.7,288,1000,1
4,Chawla's_,"Aditya Mega Mall, Karkardooma",3.4,32,800,2
...,...,...,...,...,...,...
624,Street Foods by Punjab Grill,"Worldmark 1, Aerocity",3.2,17,600,2
625,Subway,"Worldmark 1, Aerocity",3.1,25,500,3
626,Annapurna Sweets,Yusuf Sarai,3.9,109,150,1
627,Karnataka,Yusuf Sarai,3.7,334,500,2
628,EDC Mania,Yusuf Sarai,3.3,39,150,3

In [82]:
q10 = """
SELECT
    "Restaurant Name",
    "Locality",
    "Aggregate rating",
    "Votes",
    "Cuisines",
    "Average Cost for two"

FROM restaurants

WHERE "City" = 'New Delhi'
  AND "Votes" > 0

ORDER BY "Votes" DESC
LIMIT 20;
"""

result = run_query(q10)
result

,Restaurant Name,Locality,Aggregate rating,Votes,Cuisines,Average Cost for two
0,Hauz Khas Social,Hauz Khas Village,4.3,7931,"Continental, American, Asian, North Indian",1600
1,Saravana Bhavan,Connaught Place,4.3,5172,South Indian,500
2,Big Chill,Khan Market,4.5,4986,"Italian, Continental, European, Cafe",1500
3,Warehouse Cafe,Connaught Place,3.7,4914,"American, Continental, Italian, North Indian, ...",1500
4,Karim's,Jama Masjid,4.0,4689,"Mughlai, North Indian",800
5,Gulati,Pandara Road Market,4.4,4373,"North Indian, Mughlai",1500
6,Ricos,Delhi University-GTB Nagar,4.3,4085,"Cafe, Mexican, American, Italian, Lebanese, Co...",900
7,Big Yellow Door,Vijay Nagar,4.3,3986,"Cafe, Italian, Fast Food",600
8,Out Of The Box,Hauz Khas Village,3.7,3697,"American, North Indian, European, Asian",1800
9,Wenger's,Connaught Place,4.3,3591,"Bakery, Fast Food, Desserts",400
10,Rajinder Da Dhaba,Safdarjung,4.3,3530,"North Indian, Mughlai, Chinese",800
11,The All American Diner,Lodhi Colony,4.1,3495,"American, Fast Food",1000
12,The Vault Cafe,Connaught Place,3.9,3413,"North Indian, Mediterranean, Asian, Continental",1600
13,Big Yellow Door,Satyaniketan,4.2,3311,"Cafe, Fast Food, Italian",600
14,Cha Bar,Connaught Place,3.9,3206,Cafe,500
15,Barbeque Nation,Connaught Place,4.1,3164,"North Indian, Chinese",1600
16,My Bar Headquarters,Connaught Place,3.7,3010,"North Indian, Mughlai, Chinese",1000
17,Andhra Bhavan,Feroze Shah Road,4.2,3010,"South Indian, Andhra",200
18,The Flying Saucer Cafe,"Epicuria Food Mall, Nehru Place",4.3,3002,"Italian, Mediterranean, Continental, North Indian",1600
19,Khan Chacha,Khan Market,3.7,2860,"Mughlai, North Indian",650

In [83]:
q11 = """
WITH median_votes AS (
    SELECT
        PERCENTILE_CONT(0.5)
        WITHIN GROUP (ORDER BY "Votes") AS median_vote_count
    FROM restaurants
    WHERE "City" = 'New Delhi'
)

SELECT
    r."Restaurant Name",
    r."Locality",
    r."Aggregate rating",
    r."Votes",
    r."Cuisines",
    r."Average Cost for two"

FROM restaurants r
CROSS JOIN median_votes m

WHERE r."City" = 'New Delhi'
  AND r."Aggregate rating" >= 4.0
  AND r."Votes" < m.median_vote_count
  AND r."Votes" > 0

ORDER BY
    r."Aggregate rating" DESC,
    r."Votes" ASC

LIMIT 20;
"""

result = run_query(q11)
result

,Restaurant Name,Locality,Aggregate rating,Votes,Cuisines,Average Cost for two
0,Bistro 57,Netaji Subhash Place,4.0,20,"Fast Food, Beverages",500

In [84]:
q12 = """
SELECT
    "Locality",

    COUNT(*) AS restaurant_count,

    ROUND(
        AVG("Aggregate rating")::numeric,
        2
    ) AS average_rating,

    SUM("Votes") AS total_votes,

    ROUND(
        AVG("Votes")::numeric,
        0
    ) AS average_votes

FROM restaurants

WHERE "City" = 'New Delhi'
  AND "Aggregate rating" > 0

GROUP BY "Locality"

HAVING COUNT(*) >= 10

ORDER BY average_votes DESC

LIMIT 15;
"""

result = run_query(q12)
result

,Locality,restaurant_count,average_rating,total_votes,average_votes
0,Hauz Khas Village,24,3.85,32573,1357
1,Connaught Place,119,3.78,128107,1077
2,Pandara Road Market,10,3.86,7978,798
3,Khan Market,43,3.80,28463,662
4,"DLF Place Mall, Saket",12,3.70,5920,493
5,Jama Masjid,18,3.56,7411,412
6,Vijay Nagar,31,3.61,12271,396
7,"Epicuria Food Mall, Nehru Place",20,3.51,7446,372
8,"Select Citywalk Mall, Saket",25,3.76,9054,362
9,Delhi University-GTB Nagar,54,3.30,19479,361
10,Kailash Colony,13,3.50,3785,291
11,Janpath,33,3.57,9125,277
12,Rajouri Garden,98,3.63,25689,262
13,Lodhi Road,14,3.29,3311,237
14,Lodhi Colony,30,3.29,6502,217

In [85]:
q13 = """
WITH locality_stats AS (
    SELECT
        "Locality",
        AVG("Aggregate rating") AS locality_avg_rating
    FROM restaurants
    WHERE "City" = 'New Delhi'
      AND "Aggregate rating" > 0
    GROUP BY "Locality"
)

SELECT
    r."Restaurant Name",
    r."Locality",
    r."Aggregate rating",

    ROUND(
        ls.locality_avg_rating::numeric,
        2
    ) AS locality_avg_rating,

    ROUND(
        (r."Aggregate rating" - ls.locality_avg_rating)::numeric,
        2
    ) AS rating_vs_locality

FROM restaurants r

JOIN locality_stats ls
    ON r."Locality" = ls."Locality"

WHERE r."City" = 'New Delhi'
  AND r."Aggregate rating" > 0

ORDER BY rating_vs_locality DESC

LIMIT 20;
"""

result = run_query(q13)
result

,Restaurant Name,Locality,Aggregate rating,locality_avg_rating,rating_vs_locality
0,Masala Library,Janpath,4.9,3.57,1.33
1,Sita Ram Diwan Chand,Paharganj,4.3,3.00,1.30
2,Spezia Bistro,Delhi University-GTB Nagar,4.6,3.30,1.30
3,Natural Ice Cream,Hauz Khas,4.5,3.25,1.25
4,Food Scouts,Punjabi Bagh,4.6,3.39,1.21
5,Oh! Calcutta,Nehru Place,4.4,3.20,1.20
6,Midnight Hunger Hub,Janakpuri,4.5,3.32,1.18
7,Kopper Kadai,Rajouri Garden,4.8,3.63,1.17
8,Echoes Satyaniketan,Satyaniketan,4.7,3.53,1.17
9,Dukes Pastry Shop,Rajinder Nagar,4.2,3.06,1.14
10,Blue Tokai Coffee Roasters,Saket,4.4,3.26,1.14
11,London Street Kitchen,Rajinder Nagar,4.2,3.06,1.14
12,Dilli Treat,Rajinder Nagar,4.2,3.06,1.14
13,Natural Ice Cream,"JMD Kohinoor Mall, Greater Kailash",4.5,3.38,1.12
14,Naturals Ice Cream,Connaught Place,4.9,3.78,1.12
15,The Hudson Cafe,Delhi University-GTB Nagar,4.4,3.30,1.10
16,Vintro,"V3S Mall, Laxmi Nagar",3.9,2.82,1.08
17,The Barbeque Company,Jail Road,4.2,3.12,1.08
18,Lotus Pond,New Friends Colony,4.2,3.13,1.07
19,Naturals Ice Cream,Rajouri Garden,4.7,3.63,1.07

In [87]:
q14 = """WITH rating_stats AS (
    SELECT
        AVG("Aggregate rating") AS overall_avg_rating,
        PERCENTILE_CONT(0.75)
        WITHIN GROUP (ORDER BY "Votes") AS min_votes
    FROM restaurants
    WHERE "City" = 'New Delhi'
      AND "Aggregate rating" > 0
      AND "Votes" > 0
),

weighted_restaurants AS (
    SELECT
        r."Restaurant Name",
        r."Locality",
        r."Cuisines",
        r."Aggregate rating",
        r."Votes",
        r."Average Cost for two",

        ROUND(
            (
                (
                    r."Votes"::numeric
                    / (r."Votes" + s.min_votes)
                ) * r."Aggregate rating"
                +
                (
                    s.min_votes
                    / (r."Votes" + s.min_votes)
                ) * s.overall_avg_rating
            )::numeric,
            3
        ) AS weighted_rating

    FROM restaurants r
    CROSS JOIN rating_stats s

    WHERE r."City" = 'New Delhi'
      AND r."Aggregate rating" > 0
      AND r."Votes" > 0
)

SELECT
    "Restaurant Name",
    "Locality",
    "Cuisines",
    "Aggregate rating",
    "Votes",
    "Average Cost for two",
    weighted_rating
FROM weighted_restaurants
ORDER BY weighted_rating DESC
LIMIT 20;"""

result = run_query(q14)
result

,Restaurant Name,Locality,Cuisines,Aggregate rating,Votes,Average Cost for two,weighted_rating
0,Naturals Ice Cream,Connaught Place,Ice Cream,4.9,2620,150,4.830
1,Indian Accent - The Manor,Friends Colony,Modern Indian,4.9,1934,4000,4.806
2,Echoes Satyaniketan,Satyaniketan,"Cafe, Continental, Italian, Mexican, Chinese, ...",4.7,1563,600,4.600
3,Masala Library,Janpath,Modern Indian,4.9,408,5000,4.536
4,The California Boulevard,Rajouri Garden,"American, Asian, European, Seafood",4.6,1691,2000,4.514
5,Big Chill,Khan Market,"Italian, Continental, European, Cafe",4.6,1569,1500,4.507
6,Cafeteria & Co.,Vijay Nagar,"Continental, Mexican",4.6,1136,900,4.476
7,Big Chill,Khan Market,"Italian, Continental, European, Cafe",4.5,4986,1500,4.472
8,Spezia Bistro,Delhi University-GTB Nagar,"Cafe, Continental, Chinese, Italian",4.6,1071,900,4.469
9,Cafe Lota,Pragati Maidan,"North Indian, South Indian, Bihari",4.5,2213,1200,4.438
10,Naturals Ice Cream,Rajouri Garden,Ice Cream,4.7,474,150,4.417
11,Coast Cafe,Hauz Khas Village,"Continental, Kerala",4.5,1033,1400,4.375
12,Gulati,Pandara Road Market,"North Indian, Mughlai",4.4,4373,1500,4.371
13,Bukhara - ITC Maurya,"ITC Maurya, Chanakyapuri",North Indian,4.4,2826,6500,4.355
14,Big Chill,"DLF Place Mall, Saket","Italian, Continental, European, Cafe",4.4,2777,1500,4.354
15,Qubitos - The Terrace Cafe,Rajouri Garden,"Thai, European, Mexican, North Indian, Chinese...",4.5,778,1500,4.339
16,Farzi Cafe,Connaught Place,Modern Indian,4.4,1942,2200,4.336
17,Lights Camera Action - Air Bar,Rajouri Garden,"North Indian, Continental",4.4,1636,1300,4.325
18,The Hudson Cafe,Delhi University-GTB Nagar,"Cafe, Italian, Continental, Chinese",4.4,1537,850,4.320
19,Big Chill,Kailash Colony,"Italian, Continental, European, Cafe",4.4,1521,1500,4.319